blank_issues_enabled: true
contact_links:
  - name: Questions & Support
    url: https://github.com/deanlongstaff/home-assistant-moodo-integration/discussions
    about: Ask questions and get help from the community
  - name: Moodo Official Support
    url: https://moodo.co/support
    about: Contact Moodo for device-related issues
