name: Feature Request
description: Suggest an idea or enhancement for the Moodo integration
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below with as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: I've considered...
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - New entity type
        - Enhancement to existing entity
        - New device capability
        - Configuration option
        - User interface improvement
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: device-model
    attributes:
      label: Moodo Device Model
      description: Which Moodo device model is this feature for?
      options:
        - All devices
        - Moodo v1
        - Moodo v2
        - Moodo v3 (AIR)
        - Other/Unknown
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature
      placeholder: I would use this feature to...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request here

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked existing issues to ensure this feature hasn't been requested before
        - label: This feature would be useful to other users (not just me)
