name: Tests

on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_test.txt

      - name: Run tests with pytest
        run: |
          pytest tests/ -v --cov=custom_components/moodo --cov-report=term-missing --junitxml=pytest-report.xml

      - name: Publish Test Report
        if: matrix.python-version == '3.12'
        uses: dorny/test-reporter@v2
        with:
          name: Pytest Results
          path: pytest-report.xml
          reporter: jest-junit
          fail-on-error: false
